// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ngEmployee.API.Models;

namespace ngEmployee.API.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    partial class EmployeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("ngEmployee.API.Models.Employee", b =>
                {
                    b.Property<long>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1L,
                            DateOfBirth = new DateTime(1985, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kunal.ahmedabad@gmail.com",
                            FirstName = "Krunal",
                            LastName = "Parmar",
                            PhoneNumber = "+91-9833265024"
                        },
                        new
                        {
                            EmployeeId = 2L,
                            DateOfBirth = new DateTime(1988, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kinnari.solanki88@gmail.com",
                            FirstName = "Kinnari",
                            LastName = "Solanki",
                            PhoneNumber = "+91-9004558812"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
